import type { SearchItem } from "@/shared/lib/search";

export const SEARCH_MOCK_ITEMS: SearchItem[] = [
  {
    id: "proj-1",
    type: "project",
    title: "Тихий вечер",
    subtitle: "Пиксельный пейзаж · опубликовано",
    tags: ["вечер", "неон", "город"],
    href: "/editor/proj-1",
  },
  {
    id: "proj-2",
    type: "project",
    title: "Ресторан",
    subtitle: "Интерьер · черновик",
    tags: ["интерьер", "еда", "свет"],
    href: "/editor/proj-2",
  },
  {
    id: "proj-3",
    type: "project",
    title: "Первый огонёк",
    subtitle: "Сцена · черновик",
    tags: ["огонь", "ночь"],
    href: "/editor/proj-3",
  },
  {
    id: "proj-4",
    type: "project",
    title: "Неоновый переулок",
    subtitle: "Киберпанк · опубликовано",
    tags: ["неон", "дождь", "улица"],
    href: "/editor/proj-4",
  },
  {
    id: "obj-1",
    type: "object",
    title: "Фонарь",
    subtitle: "Окружение · 16×32",
    tags: ["свет", "улица"],
    href: "/objects/obj-1",
  },
  {
    id: "obj-2",
    type: "object",
    title: "Стол ресторана",
    subtitle: "Проп · 32×32",
    tags: ["мебель", "еда"],
    href: "/objects/obj-2",
  },
  {
    id: "obj-3",
    type: "object",
    title: "Персонаж Ruslan",
    subtitle: "Герой · 24×32",
    tags: ["npc", "портрет"],
    href: "/objects/obj-3",
  },
  {
    id: "obj-4",
    type: "object",
    title: "Окно с дождём",
    subtitle: "Окружение · 48×48",
    tags: ["погода", "неон"],
    href: "/objects/obj-4",
  },
  {
    id: "user-1",
    type: "user",
    title: "Ruslan",
    subtitle: "Художник · 128 работ",
    tags: ["pixel", "artist"],
    href: "/cabinet/ruslan",
  },
  {
    id: "user-2",
    type: "user",
    title: "Mira Pixel",
    subtitle: "Дизайнер · 54 работы",
    tags: ["ui", "pixel"],
    href: "/cabinet/mira",
  },
  {
    id: "user-3",
    type: "user",
    title: "Kai Neon",
    subtitle: "Иллюстратор · 77 работ",
    tags: ["неон", "city"],
    href: "/cabinet/kai",
  },
  {
    id: "tag-1",
    type: "tag",
    title: "неон",
    subtitle: "24 проекта",
    href: "/discover?tag=neon",
  },
  {
    id: "tag-2",
    type: "tag",
    title: "вечер",
    subtitle: "11 проектов",
    href: "/discover?tag=evening",
  },
  {
    id: "tag-3",
    type: "tag",
    title: "интерьер",
    subtitle: "9 проектов",
    href: "/discover?tag=interior",
  },
  {
    id: "tag-4",
    type: "tag",
    title: "киберпанк",
    subtitle: "17 проектов",
    href: "/discover?tag=cyberpunk",
  },
];
